services:
  app:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # Переменные для подключения к MySQL
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: sneakers_db
      DB_USER: root
      DB_PASSWORD: root
      # Порт приложения
      PORT: 3000
      # Режим работы
      NODE_ENV: development
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      # Синхронизация кода для hot-reload (в разработке)
      - ./back:/app
      # Защита node_modules от перезаписи (особенно на Windows/Mac)
      - /app/node_modules

  mysql:
    image: mysql:8.0
    container_name: mysql_sneakers
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sneakers_db
    ports:
      - "3306:3306" # Для подключения из DBeaver, VS Code и т.д.
    volumes:
      # Сохранение данных между перезапусками
      - ./mysql/mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


